--- 
title: "Red Hat Satellite Cheat Sheet"
description: "Cheat sheet for Red Hat Satellite"
date: "2020-04-15"
doctype: book


authors: [Toni Schmidbauer]
type: post
draft: false
categories:
   - Other
tags: ["Satellite"]

aliases: [ 
	 "/posts-output/2020-04-15-satellite-cheatsheet/",
] 
---

:imagesdir: /general/images/
:icons: font
:toc:


Cheat sheet for various Red Hat Satellite tasks from a newbie to a newbie.

<!--more--> 

== Requirements

- up to Satellite 6.7 RHEL 7.X
- 4 CPU Cores
- 20 GB of RAM
- 300 GB disk space

for more info see the https://access.redhat.com/documentation/en-us/red_hat_satellite/6.6/html/installing_satellite_server_from_a_connected_network/preparing_your_environment_for_installation#storage_requirements[prerequistes guide]

== Installation

Satellite up to version 6.7 uses puppet for installation. You can use

[source,bash]
---------
puppet filebucket
---------

to restore files modified by puppet.

Satellite requires the _Red Hat Satellite Infrastructure Subscription_, check if it's available with

[source,bash]
----------
subscription-manager list --all --available --matches 'Red Hat Satellite Infrastructure Subscription'
----------

If not attach it with

[source,bash]
-------
subscription-manager attach --pool=pool_id
-------

Next disable all repos and enable only supported repostories via

[source,bash]
-------
subscription-manager repos --disable "*"
-------

and enable required repositories

[source,bash]
----------
subscription-manager repos --enable=rhel-7-server-rpms \
--enable=rhel-7-server-satellite-6.6-rpms \
--enable=rhel-7-server-satellite-maintenance-6-rpms \
--enable=rhel-server-rhscl-7-rpms \
--enable=rhel-7-server-ansible-2.8-rpms
----------

then clean cached all repo data via

[source,bash]
-------
 yum clean all
-------

and install satellite packages via

[source,bash]
-------
yum install satellite
-------

Install satellite with

[source,bash]
-----------
satellite-installer --scenario satellite \
--foreman-initial-organization "initial_organization_name" \
--foreman-initial-location "initial_location_name" \
--foreman-initial-admin-username admin_user_name \
--foreman-initial-admin-password admin_password
-----------

== Backup / Restore / Cloning

Use `satellite-maintain` for doing offline and online backups

[source,bash]
----------
satellite-maintain backup offline /backup/
----------

when using the _online_ option make sure that no new content view or
content view versions should be created while the backup is
running. basically satellite should be idle.

=== Cloning Satellite

The online/offline options also backup _/var/lib/pulp_, which contains
all downloaded packages. This could be *huge*. There's an option to skip this so

[source,bash]
----------
satellite-maintain backup offline --skip-pulp-tar /backup/
----------

NOTE: For a restore you always need the content of _/var/lib/pulp_.

This is mainly usefull for cloning satellite. You backup everything
except _/var/lib/pulp_, copy the backup to a second system and rsync
_/var/lib/pulp_ to the new system. Then restore the backup and
satellite should work as normal on the clone.

=== Snaphot backups

Satellite also supports backups via LVM snapshots. For more information see https://access.redhat.com/documentation/en-us/red_hat_satellite/6.6/html/administering_red_hat_satellite/chap-red_hat_satellite-administering_red_hat_satellite-backup_and_disaster_recovery#snapshot-backup_assembly[Snapshot backup]

== Upgrades

. Read the Satellite release notes
. Do a offline backup see <<Backup / Restore>>
. You could clone satellite to a other system
. If there are local changes to dhcpd or dns configurations use
+
[source,bash]
----------
satellite-installer --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false
----------
+
to stop satellite-install from overwriting those files.
+
. install the latest version of satellite-maintain via
+
[source,bash]
----------
yum install rubygem-foreman_maintain
----------
+
. check for available satellite versions with
+
[source,bash]
----------
satellite-maintain upgrade list-versions
----------
+
. test the possible upgrade with
+
[source,bash]
----------
satellite-maintain upgrade check --target-version 6.7
----------
+
. and finally run the upgrade and PRAY!
+
[source,bash]
----------
satellite-maintain upgrade run --target-version 6.7
----------

== Various tips and tricks

=== Installing packages via yum

Satellite installs a yum plugin called `foreman-protector`. If you try
to install a package via yum you get the following message

[source]
---------
WARNING: Excluding 12190 packages due to foreman-protector.
Use foreman-maintain packages install/update <package>
to safely install packages without restrictions.
Use foreman-maintain upgrade run for full upgrade.
---------

so use

[source,bash]
----------
satellite-maintain install <package name>
----------

=== OS package upgrade

This should be done via satellite-maintain because all packages are locked by default (see <<Installing packages via yum>>).

This basically comes down to running

[source,bash]
----------
oreman-maintain upgrade run --target-version 6.6.z
----------

for upgrading OS packages if you have satellite 6.6 installed.
