--- 
title: "Secrets Management - Vault on OpenShift"
description: "Secrets Management with HashiCorp Vault"
date: "2022-08-16"
doctype: book

author: Thomas Jungbauer
type: post
categories:
   - OpenShift
   - Day-2
   - Gitops
   - ArgoCD
tags: ["OCP", "Day-2", "OpenShift", "Vault", "ArgoCD", "Gitops", "Secrets"] 

aliases: [ 
	 "/openshift/day-2/secrets-management",
] 
---

:imagesdir: /Day-2/images/
:icons: font
:toc:

Sensitive information in OpenShift or Kubernetes are stored as so-called Secrets. The management of these Secrets is one of the most important questions, 
when it comes to OpenShift. Secrets objects in Kubernetes are encoded in base64. This is *not* and encryption format. 
Everybody can decode a given base64 string. 

For example: `Thomas` encoded as base64 is `VGhvbWFzCg==`. This is a simply a masked plain text and it is not secure to share these values. To make your CI/CD pipelines or Gitops process secure, you 
need to think of a secure way to manage your Secrets. Thus your Secrets objects must be encrypted somehow. HashiCorp Vault is one option to achieve this requirement. 

<!--more--> 

== HashiCorp Vault
HashiCorp Vault is a solution to solve our Secret management problem.  It stores and encrypts our sensitive information at rest and in transit and enables you to create fine grained access 
controls (ACL). This defines who has access to a specific secret. Application A should only get access to secret A and so on. This is just the tip of the iceberg. Vault can do much more. 
If you are interested in detail, check out the introduction video by Armon, the Co-Founder of Hashicorp Vault at: https://learn.hashicorp.com/tutorials/vault/getting-started-intro?in=vault/getting-started 

For this article we will keep it simple and cover:

* Installing HashiCorp Vault to OpenShift
* Integrating the plugin "Kubernetes Authentication" to access the Secrets 
* Accessing Secrets stored in HashiCorp Vault by an example application 

== Installing Vault 
The easiest way to install Vault is by using the support Helm chart. 

NOTE: It is assumed that Helm is installed on your system already. 

Add the Helm repository to your repo: 

[source,bash]
----
helm repo add hashicorp https://helm.releases.hashicorp.com
----

Update the repository to get the latest updates. 

[source,bash]
----
helm repo update
----

Before we install Vault, we need to create a values file to set certain variables. Let's create a file called "overwrite-values.yaml" with the following content 

[source,yaml]
----
global:
  openshift: true

server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
----

This will tell HashiCorp Vault the environment we are going to install it (OpenShift) and enables high availability with 3 replicas and enabled RAFT. 

Finally, let us deploy HashiCorp Vault into the namespace vault using the values file we have created in the previous step:

[source,bash]
----
helm upgrade --install vault hashicorp/vault --values bootstrap/vault/overwrite-values.yaml --namespace=vault --create-namespace
----

This will start the agent-injector and 3 vault-pods: 

[source,bash]
----
oc get pods -n vault

NAME                                    READY   STATUS    RESTARTS   AGE
vault-0                                 0/1     Running   0          36s
vault-1                                 0/1     Running   0          36s
vault-2                                 0/1     Running   0          36s
vault-agent-injector-74c848f67b-sq4dq   1/1     Running   0          37s
----

*  vault agent injector: detecting application with annotations that require vault agent which will get injected 
*  vault-0: vault server 

The vault servers remain in *not-ready* state until Vault has been unsealed by you. 

When you check the logs of one of the pods you will see:

[source,bash]
----
oc logs vault-0 -n vault
...
2022-08-11T12:31:22.497Z [INFO]  core: security barrier not initialized
2022-08-11T12:31:22.497Z [INFO]  core: seal configuration missing, not initialized 
----

Vault always starts out uninitialized and sealed, to protect the secrets. You need to give at least three different unseal keys in order to be able to use Vault. 

NOTE: Vault's seal mechanism uses https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing[Shamir's secret sharing^]. This is a manual process to secure the cluster if it restarts. You can use auto-unseal for specific cloud providers to bypass the manual requirement.

== Raft Storage 
During the deployment we have enabled Raft which is the integrated HA storage for Vault. Vault can use several different styles of storage backend, but when it comes to HA and Kubernetes, Raft is 
easiest one since it has no other dependencies, and it is well known inside OpenShift. etcd is using Raft as well. It is a distributed Consensus Algorithm when multiple members form a cluster and elect one leader. The leader has the responsibility to replicate everything to the followers. Since this leader election requires a majority, an odd number of cluster members must be available to ensure there is a minimum number left if a member is failing. 

== Initialize and Unseal Vault

As mentioned, the Vault Pods are not fully available yet, since Vault it currently sealed and cannot be used. The first thing to do is to initialize and unseal it. 

NOTE: The following command will login into one Pod and execute commands from there. 

Let's get the status of our Vault fist: 

[source,bash]
----
oc -n vault exec -it vault-0 -- vault operator init -status
----

This will return the message: 
`Vault is not initialized`

The following command will initialize Vault for further usage: 

[source,bash]
----
oc exec -ti -n vault vault-0 -- vault operator init -format=json > unseal.json
----

This will create the file *unseal.json* locally on your machine. *Keep this file secure* 

CAUTION: Keep this file secure, it contains keys to unseal Vault and the root_token to authenticate against. 

Never share this file. It will look like this: 

[source,json]
----
{
  "unseal_keys_b64": [
    "key_1",
    "key_2",
    "key_3",
    "key_4",
    "key_5"
  ],
  "unseal_keys_hex": [
    "key_hex_1",
    "key_hex_2",
    "key_hex_3",
    "key_hex_4",
    "key_hex_5"
  ],
  "unseal_shares": 5,
  "unseal_threshold": 3,
  "recovery_keys_b64": [],
  "recovery_keys_hex": [],
  "recovery_keys_shares": 5,
  "recovery_keys_threshold": 3,
  "root_token": "root.token"
}
----

With the initialization in place Vault is put into a sealed mode. This means Vault cannot decrypt secrets at this moment. 
The unseal Vault you need the unseal key, which is split into multiple shards using https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing[Shamir's secret sharing^]. A certain number of individual shards (default 3) must be provided to reconstruct the unseal key. 

To unseal Vault lets login to our Pod "vault-0" and unseal it. Use the following command and provide one of the keys:

[source,bash]
----
oc exec -ti -n vault vault-0 -- vault operator unseal

Unseal Key (will be hidden):
Key                Value
---                -----
Seal Type          shamir
Initialized        true <1>
Sealed             true <2>
Total Shares       5 
Threshold          3
Unseal Progress    1/3 <3>
Unseal Nonce       08b01535-be15-e865-251c-f948ed0661c9
Version            1.11.2
Build Date         2022-07-29T09:48:47Z
Storage Type       raft
HA Enabled         true
----
<1> Vault is initialized
<2> Vault is still sealed 
<3> The unseal progress: Currently 1 out of 3 keys have been provided

Use the same command another 2 times using different keys to complete the unseal process: 

At the end the following output should be shown: 

[source,bash]
----
Unseal Key (will be hidden):
Key                     Value
---                     -----
Seal Type               shamir
Initialized             true
Sealed                  false <1>
Total Shares            5
Threshold               3
Version                 1.11.2
Build Date              2022-07-29T09:48:47Z
Storage Type            raft
Cluster Name            vault-cluster-f7402e5b <2>
Cluster ID              aff648f0-b3a2-1fdd-12f6-492842b08b2b
HA Enabled              true
HA Cluster              https://vault-0.vault-internal:8201
HA Mode                 active <3>
Active Since            2022-08-16T07:20:45.828215961Z
Raft Committed Index    36
Raft Applied Index      36
----
<1> Vault is now unsealed 
<2> Name of our cluster
<3> High availability is enabled 

*Vault-0* is now initialized, but there are 2 other members in our HA cluster which must be added. 
Let *vault-1* and *vault-2* join the cluster and perform the same unseal process as previously: use 3 different keys: 

[source,bash]
----
oc exec -ti vault-1 -n vault -- vault operator raft join http://vault-0.vault-internal:8200

# 3 times....
oc exec -ti vault-1 -n vault -- vault operator unseal

oc exec -ti vault-2 -n vault -- vault operator raft join http://vault-0.vault-internal:8200

# 3 times...
oc exec -ti vault-2 -n vault -- vault operator unseal
----

== Verify Vault Cluster
To verify if the Raft cluster has successfully been initialized, run the following.

First, login using the *root_token*, that was created above, on the vault-0 pod.

[source,bash]
----
oc exec -ti vault-0 -n vault -- vault login

Token (will be hidden): <root_token>
----

[source,bash]
----
oc exec -ti vault-0 -n vault -- vault operator raft list-peers
----

This should return:

[source,bash]
----
Node                                    Address                        State       Voter
----                                    -------                        -----       -----
16ec7490-f621-42ea-976d-5f054cfaeecc    vault-0.vault-internal:8201    leader      true
60ba2885-432a-c7d3-d280-a824f0acce42    vault-1.vault-internal:8201    follower    true
bcc4f551-79bc-47e5-d01b-97fc12d1afa5    vault-2.vault-internal:8201    follower    true
----

As you can see Vault-0 is the leader while the other two members are followers. 

== Configure Kubernetes Authentication

There are multiple ways how an application can interact with Vault. One example is to use Tokens. This is quite easy but has to bis disadvantage that it does require additional steps of managing the life cycle of such token, moreover they might be shared, which is not what we want. 

HashiCorp Vault supports different authentication methods. One of which is the *Kubernetes Auth Method* which must be enabled before we can use. 
The Kubernetes Auth Method makes use of JWTs that are bound to a Service Account. 

Vault has a plugin ecosystem, which allows to enable certain plugins. To enable *Kubernetes Auth Method* use the following process:
To configure it login to the vault-0 pod: 

1. Login vault-0 pods 
`oc exec -it vault-0 -n vault -- /bin/sh`

2. execute the command: 
`vault auth enable kubernetes` which returns:
_Success! Enabled kubernetes auth method at: kubernetes/_

3. Set up the Kubernetes configuration to use Vault's service account JWT. 

NOTE: the address to the OpenShift API (KUBERNETES_PORT_443_TCP_ADDR) is automatically available via environment variables.

[source,bash]
----
vault write auth/kubernetes/config issuer="" \
 	token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
 	kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" \
 	kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

Success! Data written to: auth/kubernetes/config
----

With this step authentication against OpenShift is enabled. 








Configure a Secret 
Vault has a seconds plugin called secret-engine, which holds the logic of renewal and revokation of secrets. 

vault secrets enable -version?2 -path=expense/static kv
