@startuml
title Ansible Execution Environments images

file "quay.io/ansible/ansible-runner:stable-2.12-latest" as base
file "quay.io/tosmi/customized-builder:latest" as builder
file "quay.io/tosmi/customized-base-ee:latest" as base_ee
file "quay.io/tosmi/customized-ee:latest" as customized_ee

' participant "build process"


builder --> base : is based on
base_ee --> base : is based on
base_ee --> customized_ee: is based on
@enduml
